name: release
on:
  push:
    branches:
      - main
      - wasm
  pull_request:
    branches:
      - main
      - wasm
jobs:
  default:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run compile
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: prepare artifacts
        run: |
          mkdir ./tmp
          find ./artifacts/contracts -name '*.json' -not -name '*.dbg.json' -exec cp {} ./tmp \;
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "package.json"
          json: |
            {
              "name": "@originpoint-at/nft_factory",
              "type": "module",
              "version": "${{ steps.package-version.outputs.current-version}}-${{ github.sha }}"
            }
          dir: 'tmp'
      - run: ls -l ./tmp
      - name: Set publishing config
        run: |-
          pnpm config set '//npm.pkg.github.com/:_authToken' "${{ secrets.GITHUB_TOKEN }}"
          pnpm config set '@originpoint-at:registry' 'https://npm.pkg.github.com'
          pnpm config list
      - run: pnpm publish --no-git-checks
        working-directory: tmp
